CREATE TABLE PEOPLE(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
KEYN VARCHAR(50));

CREATE TABLE ROLES(
NAME VARCHAR(50) NOT NULL PRIMARY KEY,
ROLE VARCHAR(50) NOT NULL,
CONSTRAINT FK_AUTHORITIES_USERS2 FOREIGN KEY(NAME)
REFERENCES PEOPLE(NAME));
COMMIT;

INSERT INTO PEOPLE VALUES('mnardone','nardone');
INSERT INTO ROLES VALUES('mnardone','ROLE_NARDONE_MEMBER');
COMMIT;