CREATE TABLE USERS(
USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(50) NOT NULL,
ENABLED BOOLEAN NOT NULL);

CREATE TABLE AUTHORITIES(
USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
AUTHORITY VARCHAR(50) NOT NULL,
CONSTRAINT FK_AUTHORITIES_USERS
FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));

CREATE TABLE GROUPS(
id BIGINT NOT NULL PRIMARY KEY,
GROUP_NAME VARCHAR(50) NOT NULL);

CREATE TABLE GROUP_MEMBERS(
group_id BIGINT NOT NULL,
username VARCHAR(50) NOT NULL);

CREATE TABLE GROUP_AUTHORITIES(
group_id BIGINT NOT NULL,
authority VARCHAR(50) NOT NULL);